// Mocks generated by Mockito 5.4.5 from annotations
// in todo/test/domain/usecase/get_all_comments_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:todo/core/error/failure.dart' as _i5;
import 'package:todo/data/models/comment_data_request.dart' as _i7;
import 'package:todo/domain/entities/comment.dart' as _i6;
import 'package:todo/domain/repositories/comments_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CommentsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommentsRepository extends _i1.Mock
    implements _i3.CommentsRepository {
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Comment>>> getComments(
          String? taskId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getComments,
          [taskId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Comment>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Comment>>(
          this,
          Invocation.method(
            #getComments,
            [taskId],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Comment>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Comment>>(
          this,
          Invocation.method(
            #getComments,
            [taskId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Comment>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Comment>> createComment(
          _i7.CommentDataRequest? comment) =>
      (super.noSuchMethod(
        Invocation.method(
          #createComment,
          [comment],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Comment>>.value(
            _FakeEither_0<_i5.Failure, _i6.Comment>(
          this,
          Invocation.method(
            #createComment,
            [comment],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i6.Comment>>.value(
                _FakeEither_0<_i5.Failure, _i6.Comment>(
          this,
          Invocation.method(
            #createComment,
            [comment],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Comment>>);
}
